name: forum_issue

env:
  INACTIVE_DAYS: 0 # Number of days since the last update to get reported as an inactive issue
  TITLE_PREFIX: Weekly forum # Issue title, followed by the date of Issue creation
  ISSUE_LABEL: weekly_forum # Label of this Issue series. This label must be exclusively used.

on:
  schedule:
    - cron: '0 8 * * 1' # For notation, see: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  forum_issue:
    permissions:
      contents: read # https://github.com/actions/checkout/issues/254
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      
      - name: Get issue info and set variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
        run: |
          hub issue --state open --format "%I%n%as%n%ur%n%ut%n%t%n%U%n%L%n" > hub_out.txt
          cat hub_out.txt
          python ./scripts/write_inactive_issue.py hub_out.txt "${{ env.INACTIVE_DAYS }}" "${{ env.ISSUE_LABEL }}" "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
          assignee_names=`ls assignee_*.txt | sed -e "s/assignee_//" -e "s/\.txt//" -e "s/[[:space:]]//g" | tr '\n' ',' | sed -e "s/,*$//"`
          echo "assignee names from assignee files: ${assignee_names}"
          echo "ASSIGNEE_TXT=$(echo ${assignee_names})" >> $GITHUB_ENV
          echo "YYYYMMDD=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
          num_close_issue=$(hub issue --state closed --format "%I%n" | wc -l | sed -e "s/[[:space:]]*//")
          echo "NUM_CLOSE_ISSUE=$(echo ${num_close_issue})" >> $GITHUB_ENV
          echo "CLOSE_ISSUE_LINK=[${num_close_issue} issues]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/issues?q=is%3Aissue+is%3Aclosed)" >> $GITHUB_ENV
          echo "OPEN_ISSUE_LINK=[open issues]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/issues)" >> $GITHUB_ENV
      - name: Read text for inactive issues
        run: |
          INACTIVE_ISSUES=$(cat assignee_*.txt)
          echo "INACTIVE_ISSUES<<EOF" >> $GITHUB_ENV
          echo "$INACTIVE_ISSUES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        id: inactive_issues
      
      - name: Create monthly forum
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: "${{ env.ASSIGNEE_TXT }}"
          labels: "${{ env.ISSUE_LABEL }}"
          title: "${{ env.TITLE_PREFIX }} ${{ env.YYYYMMDD }}"
          pinned: true
          close-previous: true
          linked-comments: false
          body: |-
            :wave: This is a lab forum for the week of ${{ env.YYYYMMDD }} for reporting and discussing miscellaneous topics. Only people who have already been assigned to other ${{ env.OPEN_ISSUE_LINK }} are automatically tagged here, but please feel free to add other members to get them notified. Please ignore this notification if it interrupts your vacation. Feature requests for this bot should be submitted [here](https://github.com/kfuku52/kflab-bot/issues). Previous weekly forum is \#{{ previousIssueNumber }} .
            
            As assignees, some of you are expected to post a recent update in the following issues (inactive period in parentheses). Please check the list, and whenever possible, close the issues with a conclusive post. So far, we have successfully closed ${{ env.CLOSE_ISSUE_LINK }} :tada: Thank you for your contributions to let our lab keep running :thumbsup:
            
            ${{ env.INACTIVE_ISSUES }}
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
