name: forum_issue

env:
  INACTIVE_SEC: 3600
  TITLE_PREFIX: Weekly forum
  ISSUE_LABEL: weekly_forum

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
        - info
        - warning
        - debug
  schedule:
    - cron: '* * 1 * *'

jobs:
  forum_issue:
    permissions:
      contents: read # https://github.com/actions/checkout/issues/254
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      
      - name: Get issue info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
        run: |
          hub issue --state open --format "%I%n%as%n%ur%n%ut%n%t%n%U%n%L%n" > hub_out.txt
          cat hub_out.txt
          python write_inactive_issue.py hub_out.txt "${{ env.INACTIVE_SEC }}" "${{ env.ISSUE_LABEL }}"
          assignee_names=`ls assignee_*.txt | sed -e "s/assignee_//" -e "s/\.txt//" -e "s/[[:space:]]//g" | tr '\n' ',' | sed -e "s/,*$//"`
          echo "assignee names from assignee files: ${assignee_names}"
          echo "ASSIGNEE_TXT=$(echo ${assignee_names})" >> $GITHUB_ENV

      - name: Set variables
        run: |
          echo "YYYYMMDD=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
      
      - name: Read text for inactive issues
        run: |
          INACTIVE_ISSUES=$(cat assignee_*.txt)
          echo "INACTIVE_ISSUES<<EOF" >> $GITHUB_ENV
          echo "$INACTIVE_ISSUES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        id: inactive_issues
      
      - name: Create monthly forum
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: "${{ env.ASSIGNEE_TXT }}"
          labels: "${{ env.ISSUE_LABEL }}"
          title: "${{ env.TITLE_PREFIX }} ${{ env.YYYYMMDD }}"
          pinned: true
          close-previous: true
          linked-comments: false
          body: |-
            :wave: This page serves as a lab forum for the week of ${{ env.YYYYMMDD }} for discussing miscellaneous topics. Only people who already have assigned issues are automatically tagged, but please feel free to add other members to get them notified. Please ignore this notification if it interrupts your vacation. Previous weekly forum is \#{{ previousIssueNumber }} .
            
            As assignees, some of you are expected to post an update in the following issues (inactive period in parentheses).
            
            ${{ env.INACTIVE_ISSUES }}
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
