name: Reminder Email

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
        - info
        - warning
        - debug
  schedule:
    - cron: '* 9 * * *'

jobs:
  reminder_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get list of Issues
        run: |
          echo "hoge"
          # get list of open Issues that haven't been updated in the past week
          #issues=$(git log --since='7 days ago' --author="$GITHUB_ACTOR" --format="%s" | grep -E "#[0-9]+")
          issues=$(git log --author="$GITHUB_ACTOR" --format="%s" | grep -E "#[0-9]+")
          echo $issues
          echo ${issues[@]}
