name: Reminder Email

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
        - info
        - warning
        - debug
  schedule:
    - cron: '* 9 * * *'

jobs:
  reminder_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get list of Issues
        run: |
          echo "hoge"
          hub issue list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
