name: Reminder Email

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
        - info
        - warning
        - debug
  schedule:
    - cron: '* * 1 * *'

jobs:
  reminder_email:
    name: hoge
    permissions:
      contents: read # https://github.com/actions/checkout/issues/254
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      
      - name: Get list of Issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
        run: |
          hub issue --state open --format "%I%n%as%n%ur%n%ut%n%t%n%U%n" > hub_out.txt
          python write_email_text.py hub_out.txt 3600
          assignee_names=( `ls assignee_*.txt | sed -e "s/assignee_//" -e "s/\.txt//"` )
          echo "assignee names from assignee files: ${assignee_names[@]}"
          echo "ISSUE_TXT=$(cat assignee_*.txt)" >> $GITHUB_ENV 
          
      - name: Get year and month
        run: echo "YYYYMM=$(date '+%Y-%m')" >> $GITHUB_ENV      
      - name: Create monthly forum
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: "kfuku52"
          labels: "monthly_forum"
          title: "Monthly forum"
          body: |-
            :wave: This page serves as a lab forum in ${{ env.YYYYMM }} for discussing miscellaneous topics.
            Before start commenting, please tag all current lab members to ensure that everyone receives notifications.
            Previous monthly forum: #{{ previousIssueNumber }}
            
            ${{ env.ISSUE_TXT }}
            
          pinned: true
          close-previous: true
          linked-comments: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
