name: Reminder Email

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
        - info
        - warning
        - debug
  schedule:
    - cron: '* 9 * * *'

jobs:
  reminder_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Get list of Issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
        run: |
          hub issue --state open --format "%I%n%as%n%ur%n%ut%n%t%n%U%n" > hub_out.txt
          python write_email_text.py hub_out.txt 3600
          assignee_names=( `ls assignee_*.txt | sed -e "s/assignee_//" -e "s/\.txt//"` )
          echo "assignee names from assignee files: ${assignee_names[@]}"
          
          git shortlog -s -n -e
          
          # https://github.com/marketplace/actions/get-github-email-from-username
          
          # https://github.com/marketplace/actions/send-email


