name: Reminder Email

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
        - info
        - warning
        - debug
  schedule:
    - cron: '* 9 * * *'

jobs:
  reminder_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get list of Issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
        run: |
          issue_txt=`hub issue --state open --format "%I%n%as%n%ur%n%ut%n%t%n%U%n"`
          issue_txt=`echo -e "${issue_txt}" | sed -e "s/^/\"/" -e "s/$/\"/"`
          issue_arr=( `echo -e "${issue_txt}"` )
          echo -e "${issue_arr[@]}"
